version: '3'

services:
  samba:
    tty: true
    network_mode: bridge
    volumes:
      - /tank/:/Shared
      - type: bind
        source: ./smb.conf
        target: /etc/smb.conf
    ports:
      - "139:139"
      - "445:445"
    build:
      context: .
      dockerfile: Dockerfile
